version: '3.1'

services:

  springapp:
    image: docker8955/spring-boot-mongo:VERSION
    restart: always # This will be ignored if we deploy in docker swarm
    ports:
    - 8080:8080
    networks:
    - springapp
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=mongodb
    - MONGO_DB_PASSWORD=mongodb@123
    depends_on:
    - mongo

  mongo:
    image: mongo:latest
    environment:
    - MONGO_INITDB_ROOT_USERNAME=mongodb
    - MONGO_INITDB_ROOT_PASSWORD=mongodb@123
    volumes:
    - springbootvol:/data/db
    restart: always
    networks:
    - springapp

volumes:
  springbootvol:
    external: true

networks:
  springapp:
    external: true


